import sys

line = sys.stdin.readline().strip()
assert line.isdigit() and line[0] != '0', f"{line} is not a valid integer"

n = int(line)

assert n >= 1, f"{n} is less than 1"
assert n <= 52, f"{n} is greater than 52"

line = sys.stdin.readline().strip()

# Validate that 'line' contains n space-seperated integers from 1 to n
nums = line.split()

assert len(nums) == n, f"Expected {n} integers, got {len(nums)}"

# Start of code generated by ChatGPT
values = []
for x in nums:
    assert x.isdigit(), f"{x} is not an integer"
    val = int(x)
    assert 1 <= val <= n, f"{val} is out of range [1, {n}]"
    values.append(val)

# Check for duplicates and completeness
assert set(values) == set(range(1, n + 1)), \
    f"Line must contain all numbers from 1 to {n} exactly once"

# End of code generated by ChatGPT

line = sys.stdin.readline()

assert len(line) == 0, f"Unexpected additional input {line}"

sys.exit(42)